# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_API_KEY }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRET_API_KEY}} | sed 's/./& /g' 
          API_KEY: ${{ secrets.SECRET_API_KEY }}
